### ISSUE TITLE
Continue Publishing Releases to Bintray

### ISSUE THREAD

**Issue by znerd** [SonarSecurityCommunity/dependency-check-sonar-plugin#102]
The README indicates that releases are deployed to Bintray. Also, the README contains a button that links to Bintray, and it indicates `1.1.1` is the latest version.

It seems no releases were published after version 1.1.1.

Suggestion:
- publish all versions after 1.1.1 to Bintray
- automate the process of publishing releases to Bintray
- make that part of the (automated? documented?) release process
- double-check how the README renders on GitHub to ensure the Bintray button refers to the appropriate version

**Comment by Reamer** [comment]
New Location https://bintray.com/sonarsecuritycommunity/owasp/sonar-dependency-check
