### ISSUE TITLE
How to verify that the results are published, getting NullPointerException on  DependencyCheckUtils.cvssToSonarQubeSeverity(DependencyCheckUtils.java:44)

### ISSUE THREAD

**Issue by MMirabito** [SonarSecurityCommunity/dependency-check-sonar-plugin#116]
Dear all,

I am hoping someone can put  me in the right direction. I am trying to integrate the results from the Dependency-Check Plugin for SonarQube 7.x. but things are getting twisted.  Here are my steps do far:

1. I use the latest ANT Dependecy-check 
[https://jeremylong.github.io/DependencyCheck/dependency-check-ant/index.html](https://jeremylong.github.io/DependencyCheck/dependency-check-ant/index.html) integrated into the build process and this appears to be working because the following files are begin generated:
- dependency-check-report.cvs
- dependency-check-report.html
- dependency-check-report.json
- dependency-check-report.xml

2. Within our Bamboo pipeline I call at Sonar task, the **sonar-project.properties** file contains
```
sonar.projectKey=XOXO

sonar.projectName=XOXO
sonar.projectVersion=1.0
 
sonar.sources=./src
sonar.java.binaries=./build/target/WebRoot/WEB-INF/classes
sonar.java.libraries=./build/target/WebRoot/WEB-INF/lib/*.jar,./build/lib/*.jar 

sonar.dependencyCheck.reportPath=./build/dependency-check-report.xml
sonar.dependencyCheck.htmlReportPath=./build/dependency-check-report.html

sonar.dependencyCheck.severity.blocker=9.0
sonar.dependencyCheck.severity.critical=7.0
sonar.dependencyCheck.severity.major=4.0
sonar.dependencyCheck.severity.minor=0.0
sonar.sourceEncoding=UTF-8
```
I get the following exception on **DependencyCheckUtils** from the build, but if set the s**everity levels to -1** no exception is throws but I cannot figure out how to verify if the results were added to sonarqube .

```
8-Mar-2019 10:07:42	10:07:42.805 DEBUG: Depedency Node license is not used
28-Mar-2019 10:07:42	10:07:42.816 INFO: ------------------------------------------------------------------------
28-Mar-2019 10:07:42	10:07:42.816 INFO: EXECUTION FAILURE
28-Mar-2019 10:07:42	10:07:42.816 INFO: ------------------------------------------------------------------------
28-Mar-2019 10:07:42	10:07:42.816 INFO: Total time: 21.180s
28-Mar-2019 10:07:42	10:07:42.966 ERROR: Error during SonarQube Scanner execution
28-Mar-2019 10:07:42	10:07:42.966 INFO: Final Memory: 22M/321M
28-Mar-2019 10:07:42	10:07:42.966 INFO: ------------------------------------------------------------------------
28-Mar-2019 10:07:42	java.lang.NullPointerException
28-Mar-2019 10:07:42	        at org.sonar.dependencycheck.base.DependencyCheckUtils.cvssToSonarQubeSeverity(DependencyCheckUtils.java:44)
28-Mar-2019 10:07:42	        at org.sonar.dependencycheck.base.DependencyCheckUtils.cvssToSonarQubeSeverity(DependencyCheckUtils.java:62)
28-Mar-2019 10:07:42	        at org.sonar.dependencycheck.DependencyCheckSensor.addIssue(DependencyCheckSensor.java:77)
28-Mar-2019 10:07:42	        at org.sonar.dependencycheck.DependencyCheckSensor.addIssues(DependencyCheckSensor.java:185)
28-Mar-2019 10:07:42	        at org.sonar.dependencycheck.DependencyCheckSensor.execute(DependencyCheckSensor.java:247)
28-Mar-2019 10:07:42	        at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
28-Mar-2019 10:07:42	        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
28-Mar-2019 10:07:42	        at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
28-Mar-2019 10:07:42	        at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
28-Mar-2019 10:07:42	        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
28-Mar-2019 10:07:42	        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
28-Mar-2019 10:07:42	        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
28-Mar-2019 10:07:42	        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
28-Mar-2019 10:07:42	        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:359)
28-Mar-2019 10:07:42	        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:354)
28-Mar-2019 10:07:42	        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:317)
28-Mar-2019 10:07:42	        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
28-Mar-2019 10:07:42	        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
28-Mar-2019 10:07:42	        at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:128)
28-Mar-2019 10:07:42	        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
28-Mar-2019 10:07:42	        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
28-Mar-2019 10:07:42	        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
28-Mar-2019 10:07:42	        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
28-Mar-2019 10:07:42	        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
28-Mar-2019 10:07:42	        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
28-Mar-2019 10:07:42	        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
28-Mar-2019 10:07:42	        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
28-Mar-2019 10:07:42	        at java.lang.reflect.Method.invoke(Method.java:498)
28-Mar-2019 10:07:42	        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
28-Mar-2019 10:07:42	        at com.sun.proxy.$Proxy0.execute(Unknown Source)
28-Mar-2019 10:07:42	        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
28-Mar-2019 10:07:42	        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
28-Mar-2019 10:07:42	        at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
28-Mar-2019 10:07:42	        at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
28-Mar-2019 10:07:42	        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
28-Mar-2019 10:07:43	Failing task since return code of [D:\MyPrograms\sonar-scanner-3.3.0.1492-windows\bin\sonar-scanner.bat -X -Dsonar.host.url=https://myserver.xxx.com/SONARQUBE -Dsonar.login=****** -Dsonar.password=****** -Dsonar.branch=master] was 1 while expected 0
28-Mar-2019 10:07:43	SONAR4BAMBOO: was not able to find a SonarQube result URL
28-Mar-2019 10:07:43	Finished task 'Scan Code' with result: Failed

```

3. Our environment is:
```
Bamboo 6.81 
SonarQube 7.7
dependency-check-ant-5.0.0-M2
dependency-check-sonar-plugin 1.2.2 Snapshot  - built from source
```

Thank in advance for any guidance.

max

**Comment by Reamer** [comment]
Hi @MMirabito,
this plugins doesn't work at the moment with Sonarqube 7.7 and Sonarqube 7.6 Please take a look into https://github.com/stevespringett/dependency-check-sonar-plugin/issues/106

We will try to fix this. See for this https://github.com/stevespringett/dependency-check-sonar-plugin/pull/99
If you can't wait, you can build the plugin on your own, on my [working branch](https://github.com/Reamer/dependency-check-sonar-plugin/tree/sonarwork). In general it should work. I'll only add some unit tests before pushing my changes to this repository.

**Comment by Reamer** [comment]
Which java version your using? The NullPointerException should not happen on this line.

**Comment by MMirabito** [comment]
> Hi @MMirabito,
> this plugins doesn't work at the moment with Sonarqube 7.7 and Sonarqube 7.6 Please take a look into #106
> 
> We will try to fix this. See for this #99
> If you can't wait, you can build the plugin on your own, on my [working branch](https://github.com/Reamer/dependency-check-sonar-plugin/tree/sonarwork). In general it should work. I'll only add some unit tests before pushing my changes to this repository.

Hi @Reamer thanks for the quick reply will give that a try any idea when you might a full release compatible with 7.7.

thanks, 
max

**Comment by MMirabito** [comment]
@Reame,

I glanced at the code very quickly where the exception was occurring and noticed that if changed the following:

```
sonar.dependencyCheck.severity.blocker=-1
sonar.dependencyCheck.severity.critical=-1
sonar.dependencyCheck.severity.major=-1
sonar.dependencyCheck.severity.minor=-1
```

Then the exception does not occur but it doe snot appear the the stuff gets uploaded into sonarqube.

max

**Comment by Reamer** [comment]
It seems that in this line https://github.com/stevespringett/dependency-check-sonar-plugin/blob/master/sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/base/DependencyCheckUtils.java#L44
`cvssScore` is null, therefore the NullPointerException

**Comment by Reamer** [comment]
Which version of the Dependecy-check Ant your using? If you use a 5.x, please downgrade to a 4.x. In 5.x the xml schema changed.

**Comment by Reamer** [comment]
I created a new issue, which I think effects you https://github.com/stevespringett/dependency-check-sonar-plugin/issues/117

**Comment by MMirabito** [comment]
We are using dependency-check-ant-5.0.0-M2 and will downgrade to the older version thanks for pointing it out.

max

**Comment by MMirabito** [comment]
Hi @Reamer, I downgraded to dependency-check-4.0.2 yesterday and iy looks like its working. 

But I still do not understand if I ma getting the expected behavior in SonarQube. The resewn I am asking is that I found a screen shot of a dashboard in [screenshot](https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin/blob/SonarQube_6.x/screenshots/dashboard-widget.png) but for some reason i cannot locate on my sonarqube instance, do you know were it is?

Attached are a few screenshots of what I am seeing when the report is posted to SonarQube, is this correct, I think I am missing the dashboard. 

Thanks again, 
max


![2019-03-30_18-06-42](https://user-images.githubusercontent.com/23298288/55282376-316c9c00-5319-11e9-8095-924789e6e172.png)
![2019-03-30_18-05-36](https://user-images.githubusercontent.com/23298288/55282377-33cef600-5319-11e9-8a38-f7abb04d30f6.png)
![2019-03-30_18-03-58](https://user-images.githubusercontent.com/23298288/55282379-3598b980-5319-11e9-9045-42dfe76ad1bb.png)

**Comment by Reamer** [comment]
Hi @MMirabito,
custom widgets were removed from sonarqube. Therefore i removed the screenshot in commit https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin/commit/e2e6d3752fc7ac0ca4284383b90f5061447efff1. The widget code was removed in #79 

With the plugin you have the HTML-Report and Measures as addtional GUI elements
![Dependency_check_Measures](https://user-images.githubusercontent.com/454320/55286399-ca43fb80-539b-11e9-8a25-fbb7679b8c67.png)

**Comment by MMirabito** [comment]
@Reamer,

Many thanks for the clarification that custom widgets were removed from sonarqube.

Thanks,
max

**Comment by Reamer** [comment]
Any other questions or can we close this issue? In issue #117 we can follow the incompatibility for dependency-check 5.x.

**Comment by MMirabito** [comment]
Everything is good so far. Once again many thanks for the explanation. Eagerly awaiting comparability with  dependency-check 5.x. and as you indicated will follow [#117](https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin/issues/117).

Thanks,
max
