### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by Kampfmoehre** [SonarSecurityCommunity/dependency-check-sonar-plugin#139]
**Describe the bug**
Upload of dependency report fails on Node project due to too large html report.

**To Reproduce**
I have some Node projects that I have successfully integrated the dependency check 4.0.2 in SonarQube. However when I create the report with Dependency-Check 5.0.0-M2, the report gets very large even on small projects. The report is about 13 MB big and on the upload to Sonarqube the request fails with the following message:

```
ERROR: Error during SonarQube Scanner execution
ERROR: Failed to upload report - HTTP code 413: <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
```

**Current behavior**
The plugin fails to upload the generated report.

**Expected behavior**
The report should be uploaded.

**Versions (please complete the following information):**
 - dependency-check 5.0.0-M2
 - sonarqube 7.7 build 23042
 - dependency-check-sonar-plugin 1.2.3

**Additional context**
Is there anything I can do, e.g. raising the limit on the SonarQube webserver or something? Is it normal for DependencyCheck to create such a large HTML file? With the 4.0.2 version the report "only" was 3 MB which SOnarqube accepted.
Here are my NPM dependencies (this project only has dev dependencies):

```
  "devDependencies": {
    "@commitlint/cli": "^7.5.2",
    "@commitlint/config-conventional": "^7.5.0",
    "@danmasta/mocha-sonar": "0.0.5",
    "@semantic-release/changelog": "^3.0.2",
    "@semantic-release/git": "^7.0.8",
    "@semantic-release/gitlab": "^3.1.2",
    "@types/chai": "^4.1.7",
    "@types/chai-as-promised": "^7.1.0",
    "@types/mocha": "^5.2.6",
    "@types/node": "^11.13.7",
    "@types/sinon": "^7.0.11",
    "chai": "^4.2.0",
    "chai-as-promised": "^7.1.1",
    "husky": "^1.3.1",
    "istanbul": "^0.4.5",
    "lint-staged": "^8.1.5",
    "mocha": "^6.1.4",
    "nyc": "^14.0.0",
    "prettier": "^1.17.0",
    "rimraf": "^2.6.3",
    "semantic-release": "^15.13.12",
    "sinon": "^7.3.2",
    "source-map-support": "^0.5.12",
    "ts-node": "^8.1.0",
    "tslint": "^5.16.0",
    "typescript": "^3.4.4"
  },
```

**Comment by arradz** [comment]
Just increase allowed upload file size in SQ Nginx setup.

**Comment by Kampfmoehre** [comment]
Thank you very much, I almost forgot about running behind a proxy.
