### ISSUE TITLE
ERROR: Metric 'critical_severity_vulns' should not be computed by a Sensor

### ISSUE THREAD

**Issue by Mobrockers** [SonarSecurityCommunity/dependency-check-sonar-plugin#146]
**Describe the bug**
When reading the dependency check XML, the sonarqube msbuild scanner throws the following error:
ERROR: Metric 'critical_severity_vulns' should not be computed by a Sensor

**Command options used to start scan**
`dependency-check.bat -f XML -f HTML --scan CompanyName.CompanyName.ProductNameAPI.Web.Website --out $(System.DefaultWorkingDirectory)/DepencyCheckReports --project CompanyName.CompanyName.ProductNameAPI.Web --noupdate --enableExperimental`

**Logs**
[dependency-check-report.txt](https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin/files/3171913/dependency-check-report.txt)
[Azure Devops SonarQube Build Logs.txt](https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin/files/3171927/Azure.Devops.SonarQube.Build.Logs.txt)

**Current behavior**
Sonarqube refuses to complete the scan because it won't accept the dependency scanner XML

**Expected behavior**
Sonarqube loads the dependency scanner XML

**Versions (please complete the following information):**
 - dependency-check 4.0.2
 - sonarqube 7.6 Developer Edition
 - dependency-check-sonar-plugin 1.1.4

**Comment by Reamer** [comment]
Hi @Mobrockers,
can you update [dependency-check-sonar-plugin to 1.2.3](https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin/releases/tag/1.2.3). 1.1.x is for sonarqube 6.7.x
Does the problem persist?

**Comment by Mobrockers** [comment]
Right. Is there a version compatibility matrix somewhere? According to the readme 1.1.4 is the latest version and this is the version marked latest in the release section. This is non-obvious, both me and my coworker failed to notice it wasn't the latest version. I would also not expect a minor version to have this much of a difference.
Also the description says 'SonarQube 6.7.5 and above' this should probably say 6.7.5 to 7.6. 

I'll try 1.2.3 tomorrow and report back.

**Comment by Reamer** [comment]
The difference between 1.2.3 and 1.1.4 are really small. 1.1.4 is compiled against Sonarqube 6 LTS and 1.2.3 against 7.6. Our plugin which support sonarqube 7.6 has one additional [feature]( https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin/commit/1f2dc6ef824d42728bbdc6108f89d5273bd2552c) to work with [Security Reports](https://docs.sonarqube.org/latest/user-guide/security-reports/).

The latest annotation is done by bintray and github. In generally I work with this newest version of Sonarqube and at some point (mostly after a release for sonarqube 7), I'll port back all changes and make a release for sonarqube 6.7.

Compatibility matrix could be hopeful. Can you provide a PR?

**Comment by Mobrockers** [comment]
@Reamer 1.2.3 does work for us, so we'll use that version instead.

I can help add some guidance to find the right plugin version. Are you fine with this information being in the readme or would you prefer it somewhere else?

**Comment by Reamer** [comment]
It's good to hear, that your problem is solved. A pull request for readme should be enough.
