### ISSUE TITLE
The "aggregate" dependency-check.xml report is not parsed correctly by sonar plugin

### ISSUE THREAD

**Issue by Prix1** [SonarSecurityCommunity/dependency-check-sonar-plugin#15]
The "aggregate" dependency-check.xml report results are distributed incorrectly on modules in multi-module sonar project. Each module has the same overall number of dependencies and vulnerabilities.

**Comment by stevespringett** [comment]
What does your configuration look like? Have you specified a single dependency-check.xml for the entire project or have you specified individual reports for each module in sonar?

**Comment by Prix1** [comment]
@stevespringett, I have multi-modules maven project and I generated dependency-check.xml via "aggregate" goal from "owasp-dependency-check" maven plugin. So I have single dependency-check.xml report for the entire project as result.Then I passed this report to sonar via sonar.dependencyCheck.reportPath=target/dependency-check-report.xml property. Eventually, I got some result in sonar. But owasp widget shows incorrect number of dependencies and  number of vulnerabilities issues is incorrect too. It seems that plugin does not distribute the vulnerabilities per modules  correctly.

**Comment by stevespringett** [comment]
For a multi-module project, you'll need to specify the dependency-check-report.xml for each module, as the aggregate report does not include which module a vulnerability was found in.

Follow the examples in https://github.com/stevespringett/dependency-check-sonar-plugin/tree/master/examples/multi-module-maven-runner for how to use in a multi-module project. If you continue to have issues with counts being incorrect, reopen this ticket or create a new one.

**Comment by Prix1** [comment]
@stevespringett, Thak you for reply. Right, I use it like you suggest. But as for me, it is pretty uncomfortable to use it in this way with sonar, because the project is opened on root module (pom) page by default in sonar dashboard and I cannot see aggregate information for all modules via widget on root page like a common best practice.

**Comment by stevespringett** [comment]
So if I understand correctly. You do not have a way to aggregate your raw dependency-check results that you would normally get from the gradle or maven plugin. You want the sonar plugin to aggregate the results for you?

Let me look into this to see if it's possible without breaking conventional dependency-check use cases.

**Comment by Prix1** [comment]
@stevespringett, right. Actually, I don't know the nuances of implementation, but I would propose the next approaches:
1. Sonar plugin aggregates the multiple report from each modules, as you mention above.
2. Add information about  vulnerabilities per modules to single aggregated report and force sonar plugin to "understand" this report (due to "the aggregate report does not include which module a vulnerability was found in.")

**Comment by bdellegrazie** [comment]
@stevespringett / @Prix1: I use `dependency-check-maven:aggregate sonar:sonar` and this in maven's settings.xml:
```
<sonar.dependencyCheck.reportPath>${project.build.directory}/dependency-check-report.xml</sonar.dependencyCheck.reportPath>
```
Essentially the plugin only picks the report up on the reactor build. On the internal module builds it doesn't report anything. This is not perfect, but it does mean the aggregate values are correct and the check is much faster (because you use the `aggregate` goal).

**Comment by Reamer** [comment]
Closing this issue, because it's quite old. With Version [1.2.2](https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin/releases/tag/1.2.2) and above only dependency-check:aggregate is supported.
