### ISSUE TITLE
Sonar qube doesn't load the plugin

### ISSUE THREAD

**Issue by FrancescoDeSimone** [SonarSecurityCommunity/dependency-check-sonar-plugin#162]
Hi,
I'm trying to add the OWASP-Dependency-Check plugin into my maven project.
I'm using sonarqube 7.9 with this property:
`
sonar.projectKey=my:project sonar.sources=./ sonar.java.binaries=target/classes sonar.dependencyCheck.reportPath=target/dependency-check-report.xml`

I set in my pom file the plugin and the directory for the target:
```
...
<dependency.check.report.dir>${project.build.directory}</dependency.check.report.dir>
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
<sonar.host.url>http://localhost:9000/</sonar.host.url><sonar.dependencyCheck.reportPath>${dependency.check.report.dir}/dependency-check-report.xml</sonar.dependencyCheck.reportPath>
<sonar.dependencyCheck.htmlReportPath>${dependency.check.report.dir}/dependency-check-report.html</sonar.dependencyCheck.htmlReportPath>
...
<plugin>
<groupId>org.owasp</groupId>
<artifactId>dependency-check-maven</artifactId>
<version>5.0.0-M3</version>
<executions><execution><goals>
<goal>check</goal>
</goals></execution></executions>
<configuration>
<format>ALL</format><outputDirectory>${dependency.check.report.dir}</outputDirectory>
</configuration>
</plugin>

```
and add the settings.xml file in the conf folder in the root of the project:
```
<settings>
    <pluginGroups>
        <pluginGroup>org.sonarsource.scanner.maven</pluginGroup>
    </pluginGroups>
    <profiles>
        <profile>
            <id>sonar</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <!-- Optional URL to server. Default value is http://localhost:9000 -->
                <sonar.host.url>
                  http://localhost:9000
                </sonar.host.url>
            </properties>
        </profile>
     </profiles>
</settings>


```
If i check in the "code tab" of sonar qube there is no target folder, so i think for some reason sonarqube exclude the directory.
Do I have to include explicitly the target folder path?

**Comment by Reamer** [comment]
The `target`-folder isn't included by default and should not included.
Check on https://docs.sonarqube.org/latest/analysis/analysis-parameters/ parameter `sonar.sources`.
Parts of the dependency-check-plugin runs on your workstation or a jenkins server. The plugin reads report files there and adds issues and several other things via sonarqube api. Therefore there is no need that the `target`-folder is included in `sonar.source`.

**Comment by Reamer** [comment]
If you provide an HTML-Report, that report will uploaded to sonarqube. You can see this report under Project-Page -> More -> Dependency-Check

**Comment by FrancescoDeSimone** [comment]
In Project-Page -> More -> Dependency-Check I've an empty page, also in measures under the OWASP-dependency-check I've nothing

**Comment by Reamer** [comment]
Can you provide debug output of the sonar-scanner run?

**Comment by FrancescoDeSimone** [comment]
I just check the output of sonar scanner and i found
`WARN: Analysis aborted due to: Mandatory elements are missing. Plugin is compatible to https://jeremylong.github.io/DependencyCheck/dependency-check.1.8.xsd, https://jeremylong.github.io/DependencyCheck/dependency-check.2.9.xsd
`
and

```
WARN: Missing blame information for the following files:
WARN: * target/classes/beans.xml
WARN: * target/classes/db/changelog/change_2.xml
WARN: * target/classes/logback-spring.xml
WARN: * target/dependency-check-junit.xml
WARN: * target/dependency-check-report.xml
```

**Comment by Reamer** [comment]
Which version of dependency-check-sonar-plugin do you use?

**Comment by FrancescoDeSimone** [comment]
sonar-dependency-check-plugin-1.1.4.
I also include sonar-maven-plugin in the pom (I forgot it)

**Comment by Reamer** [comment]
Please checkout https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin#plugin-version-compatibility
For Sonarqube 7.9 you should use [dependency-check-sonar-plugin-1.2.4](https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin/releases/tag/1.2.4)

**Comment by Reamer** [comment]
@FrancescoDeSimone Does it work with the right version?

**Comment by FrancescoDeSimone** [comment]
With the right version it woks. thanks
