### ISSUE TITLE
Does it work with sonar-scanner?

### ISSUE THREAD

**Issue by javixeneize** [SonarSecurityCommunity/dependency-check-sonar-plugin#166]
Hi

Does it work with sonar-scanner, using a parameter like -Dsonar.dependencyCheck.reportPath, or does it only work as a maven plugin as per the examples?

**Comment by Reamer** [comment]
Checkout our [nodejs example](https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin/tree/master/examples/single-module-nodejs). It should work with all variants `pom.xml` (Maven), direct ( e.g. `-Dsonar.dependencyCheck.reportPath`) and `sonar.properties`  for sonar-scanner/sonar-runner.

**Comment by javixeneize** [comment]
Thanks!
