### ISSUE TITLE
Option to separate dependency vulnerabilities from code vulnerabilities

### ISSUE THREAD

**Issue by ghost** [SonarSecurityCommunity/dependency-check-sonar-plugin#24]
Is there a way to put the dependency vulnerabilities in a separate category than code vulnerabilities? I'd like to place them in something like 'dependencies vulns' instead of 'vulnerabilities'.

The reason is there are multiple times more dependency vulns than code vulns and it is clogging up the issues, making it difficult to triage. I'm able to filter it out by language (since dep vulns are 'general' language), but it's still throwing off the vulnerability count in a lot in some of the projects.

**Comment by stevespringett** [comment]
To my knowledge, there is no way to separate them. SonarQube is designed as a quality tool for source code. The fact that Dependency-Check results are even possible in SQ is a bit of a hack. This was a directional change in SQ between 3.x and 4.x. Previously, SQ wanted to be the centralized quality dashboard. That changed with 4.x and they focused solely on code quality.

As you know, sometimes code is responsible for vulnerable dependencies, but most often it's not.

If there's a way to do what you want, I will gladly do it. Unfortunately, I just don't think it's possible. I'm marking this issues as 'Help Wanted' in the event others have similar requests and think of creative ways to hack this functionality in.

**Comment by Reamer** [comment]
This plugin is not able to configure filters. Take a look at [Security-Report](https://docs.sonarqube.org/latest/user-guide/security-reports/)
